<a href="https://colab.research.google.com/github/naugim26/2026-BDA/blob/main/code/06w_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 06 테이블 분석 패키지 pandas

## 일부 내용은 code 05파일에 함께 있음

### 6.2

In [5]:
import pandas as pd
import numpy as np

dates = pd.date_range("20260408",periods=6)
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [6]:
dates[0]

Timestamp('2026-04-08 00:00:00')

In [7]:
dates=pd.date_range("20260408",end='20250420')
dates

DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [8]:
dates=pd.date_range("20260408",periods=6,freq='3D')
dates

DatetimeIndex(['2026-04-08', '2026-04-11', '2026-04-14', '2026-04-17',
               '2026-04-20', '2026-04-23'],
              dtype='datetime64[ns]', freq='3D')

In [9]:
dates=pd.date_range("20260408",periods=6,freq='3H')
dates

/tmp/ipykernel_1688/1145539086.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates=pd.date_range("20260408",periods=6,freq='3H')

DatetimeIndex(['2026-04-08 00:00:00', '2026-04-08 03:00:00',
               '2026-04-08 06:00:00', '2026-04-08 09:00:00',
               '2026-04-08 12:00:00', '2026-04-08 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [10]:
dates=pd.date_range("20260408",periods=6,freq='W')
dates

DatetimeIndex(['2026-04-12', '2026-04-19', '2026-04-26', '2026-05-03',
               '2026-05-10', '2026-05-17'],
              dtype='datetime64[ns]', freq='W-SUN')

In [11]:
dates=pd.date_range("20260408",periods=6,freq='W-SUN')
dates

DatetimeIndex(['2026-04-12', '2026-04-19', '2026-04-26', '2026-05-03',
               '2026-05-10', '2026-05-17'],
              dtype='datetime64[ns]', freq='W-SUN')

In [12]:
dates=pd.date_range("20260408",periods=6,freq='W-THU')
dates

DatetimeIndex(['2026-04-09', '2026-04-16', '2026-04-23', '2026-04-30',
               '2026-05-07', '2026-05-14'],
              dtype='datetime64[ns]', freq='W-THU')

In [13]:
dates=pd.date_range("20260408",periods=6,freq='W-FRI')
dates

DatetimeIndex(['2026-04-10', '2026-04-17', '2026-04-24', '2026-05-01',
               '2026-05-08', '2026-05-15'],
              dtype='datetime64[ns]', freq='W-FRI')

In [14]:
dates=pd.date_range("20260408",periods=6,freq='M')
dates

/tmp/ipykernel_1688/3191251365.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates=pd.date_range("20260408",periods=6,freq='M')

DatetimeIndex(['2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31',
               '2026-08-31', '2026-09-30'],
              dtype='datetime64[ns]', freq='ME')

In [15]:
dates=pd.date_range("20260408",periods=6,freq='MS')
dates

DatetimeIndex(['2026-05-01', '2026-06-01', '2026-07-01', '2026-08-01',
               '2026-09-01', '2026-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [17]:
dates=pd.date_range("20260408",periods=6)
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [18]:
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df

                   A         B         C         D
2026-04-08 -0.508051 -1.005478 -0.431791  0.416017
2026-04-09  0.639638  0.714740 -0.691073 -0.447090
2026-04-10  0.433363  0.927475  0.964796 -0.098681
2026-04-11 -0.800079 -0.491462 -0.764113  0.079275
2026-04-12 -0.787063 -0.314054 -1.633578  0.670088
2026-04-13  0.101439  0.396464 -0.365115  0.558277

In [20]:
df2=pd.DataFrame({
    "A":1.0,
    "B":pd.Timestamp("20260408"),
    "C":pd.Series(np.arange(1,3,.5)),
    "D":np.array([3]*4,dtype="int32"),
    "E":pd.Categorical(["test","train","test","train"]),
    "F":"foo"
})
df2

     A          B    C  D      E    F
0  1.0 2026-04-08  1.0  3   test  foo
1  1.0 2026-04-08  1.5  3  train  foo
2  1.0 2026-04-08  2.0  3   test  foo
3  1.0 2026-04-08  2.5  3  train  foo

In [21]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

### 6.3 DataFrame의 다양한 참조

In [22]:
import pandas as pd
pf=pd.DataFrame(data=[[25,35,8,18],
                      [18,27,10,20],
                      [17,17,10,19],
                      [12,22,9,20],
                      [22,34,8,16]],
                index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                columns=['중간','기말','과제','출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [23]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [24]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [26]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [27]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [28]:
pf[['기말','출석','중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [29]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [30]:
pf['중간']>20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [31]:
pf[pf['중간']>20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [32]:
pf[pf['출석']>=19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [33]:
pf[(pf['출석']>=19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [36]:
import pandas as pd
pf=pd.DataFrame(data=[[25,35,8,18],
                      [18,27,10,20],
                      [17,17,10,19],
                      [12,22,9,20],
                      [22,34,8,16]],
                index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                columns=['중간','기말','과제','출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [38]:
import pandas as pd
#df.loc[]
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [39]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [40]:
pf.loc[['홍소희','윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [42]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [43]:
pf.loc[pf.중간>20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [44]:
pf.loc[(pf.중간>10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [45]:
pf.loc[pf.index[0]]

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [46]:
pf.loc[[pf.index[0]]]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [47]:
pf.loc[pf.index[1:4]]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [48]:
pf.loc[pf.index[1:4]][['기말','과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [49]:
pf.loc[:,'과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [52]:
pf.loc[:,'중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [51]:
pf.loc[:,['기말','출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [54]:
pf.loc[:,pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [55]:
pf.loc[:,[pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [56]:
pf.loc[:,pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [57]:
pf.loc[:,pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [58]:
pf.loc[:,pf.columns[1:]][['기말','과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [59]:
pf.loc['윤일형','출석']

np.int64(18)

In [89]:
pf.loc['윤일형':'유한빈','기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [63]:
pf.loc['윤일형':'유한빈','기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [65]:
pf.loc[pf.index[0],pf.columns[1]]

np.int64(35)

In [66]:
pf.loc[pf.index[0:3],pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [67]:
pf.loc[pf.index[0:3],pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

In [68]:
pf.iloc[1]

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [69]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  20

In [70]:
pf.iloc[[1,3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [71]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [73]:
pf.iloc[:,2]

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [74]:
pf.iloc[:,[2]]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [75]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [76]:
pf.iloc[1,1]

np.int64(27)

In [77]:
pf.iloc[1:3,1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [78]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [80]:
pf.iloc[[1,3,4],1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [81]:
pf.iloc[[1,3,4],[0,1]]

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [82]:
pf.at['윤일형','과제']

np.int64(8)

In [83]:
pf.at['유한빈','기말']

np.int64(22)

In [84]:
pf.at[pf.index[1],'출석']

np.int64(20)

In [86]:
pf.at[pf.index[3],pf.columns[2]]

np.int64(9)

In [87]:
pf.iat[1,2]
pf.iat[2,3]

np.int64(19)